# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e4b08498a4bde2b400610d718537b051abd2abbe13dc0e1a24679e0403d098678b2b85cccf8e740864f259b3c560789fc08bf9c6c80f2851265d94909ba26f9

test:
  secret_key_base: d44d14b2ba9e78107714fdf4144bcdda9b76920f6eba7be6517b8983f1f3410691af3ae709cdde91b925292704afc378d939542100d47abd7c75e239c6f42c1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
